export const DATE_FORMATS = [
  "yyyy-MM-dd",
  "yyyy-M-d",
  "yyyy/MM/dd",
  "yyyy/M/d",
  "yyyyMMdd",
  "EEEE, dd MMMM yyyy",
  "EEEE dd MMMM yyyy",
  "EEE, dd MMMM yyyy",
  "EEE dd MMMM yyyy",
  "dd MMMM yyyy",
  "dd-MMMM-yyyy",
  "d MMM yyyy",
  "d-MMM-yyyy",
  "dd MMM yy",
  "d MMM yy",
  "MMMM d yyyy",
  "MMM d yyyy",
  "MMM d, yyyy",
  "MM/dd/yyyy",
  "M/d/yyyy",
  "MM-dd-yyyy",
  "M-d-yyyy",
  "MM/dd/yy",
  "MM-dd-yy",
  "dd/MM/yyyy",
  "d/M/yyyy",
  "d M yyyy",
  "d MM yyyy",
  "dd.MM.yyyy",
  "d.M.yyyy",
  "dd/MM/yy",
  "dd.MM.yy",
  "d/M/yy",
  "d.M.yy",
];

export const TIME_FORMATS = [
  "HH:mm:ss",
  "HH:mm",
  "HH mm",
  "h:mm:ss a",
  "h:mm a",
  "h mm a",
  "h a",
];
